# Generated by Django 5.0.6 on 2024-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auction_id_alter_bid_id_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg",
                max_length=300,
            ),
        ),
    ]
