# Generated by Django 5.0.6 on 2024-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_starting_bid_alter_item_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=6,
            ),
        ),
    ]
