# Generated by Django 5.0.6 on 2024-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="items",
            field=models.ManyToManyField(
                related_name="watchlist", to="auctions.auction"
            ),
        ),
    ]
