# Generated by Django 5.0.6 on 2024-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_comment_auction_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
